DLP-1 User Registration
UltraMKF12/internship-laravel pull request #1
Opened 2024-04-03 11:46 UTC by UltraMKF12

2024-04-03 12:36 UTC, szabolcs3 requested changes

2024-04-03 12:36 UTC, szabolcs3 commented on app/Http/Controllers/Auth/RegisteredUserController.php
>          $request->validate([
Please use the validations [like this](https://laravel.com/docs/11.x/validation#creating-form-requests) 😄 . You don't need to define the rules here. Also be consistent use ['required', ...]

2024-04-03 12:36 UTC, szabolcs3 commented on app/Http/Controllers/Auth/RegisteredUserController.php
>          $user = User::create([
I think you can do this with one command if you `$user = User::create($request->validated())` use the validation above

2024-04-03 12:36 UTC, szabolcs3 commented on app/Http/Controllers/Auth/RegisteredUserController.php
>              'password' => Hash::make($request->password),
[Read this please 😄 ](https://ashallendesign.co.uk/blog/automatically-hash-laravel-model-values-using-the-hashed-cast)

2024-04-03 12:36 UTC, szabolcs3 commented on app/Http/Requests/Auth/LoginRequest.php
GG! 👏

2024-04-03 12:36 UTC, szabolcs3 commented on resources/js/Components/InputWithErrorAndLabel.vue
> +      <div
Can't you do this with a mapper or with slots?

2024-04-03 12:36 UTC, szabolcs3 commented on resources/js/Components/InputWithErrorAndLabel.vue
> +  if (showPassword.value) {
```
if (...) {
  ...
  return;
}
...
```
Use early returns please!

2024-04-03 12:36 UTC, szabolcs3 commented on resources/js/Pages/Auth/old/VerifyEmail.vue
> +  status?: string
Please use interface here

2024-04-03 12:36 UTC, szabolcs3 commented on resources/js/Pages/Auth/old/VerifyEmail.vue
> +    <div class="mb-4 text-sm font-medium text-green-600" v-if="verificationLinkSent">
Something isn't right with the eslint, because v-if should be the first attribute.

2024-04-03 12:36 UTC, szabolcs3 commented on resources/js/Pages/Auth/old/ResetPassword.vue
> +const props = defineProps<{
Please use interface 😄

2024-04-03 12:36 UTC, szabolcs3 commented on resources/js/Pages/Auth/old/Login.vue
> +defineProps<{
Please use interface.

2024-04-03 12:36 UTC, szabolcs3 commented on resources/js/Pages/Auth/old/ForgotPassword.vue
> +  status?: string
Please use interface.

2024-04-03 12:36 UTC, szabolcs3 commented on resources/js/Layouts/GuestLayout.vue
> +import ApplicationLogo from '@/Components/old/ApplicationLogo.vue'
What is this "old" means here?

2024-04-03 12:36 UTC, szabolcs3 commented on resources/js/Layouts/AuthenticatedLayout.vue
> +              <div class="text-sm font-medium text-gray-500">{{ $page.props.auth.user.email }}</div>
Please use the shared datas [like this (Accessing shared data)](https://inertiajs.com/shared-data)

2024-04-03 12:36 UTC, szabolcs3 commented on resources/js/Components/RegisterSidebar.vue
> +          :is-last="true"
Just use `is-last`

2024-04-03 12:36 UTC, szabolcs3 commented on resources/js/Components/RegisterSidebar.vue
> +          :is-selected="true"
Just use `is-selected`

2024-04-03 13:12 UTC, zsolt-wbg requested changes

2024-04-03 13:12 UTC, zsolt-wbg commented on resources/js/Components/SidebarStep.vue
> +      <SidebarStepIcon :is-selected="props.isSelected" :is-last="props.isLast" />
Also remove from here the props. Please modify everywhere!

2024-04-03 13:12 UTC, zsolt-wbg commented on resources/js/Pages/Auth/old/ForgotPassword.vue
> +          v-model="form.email"
Please pay attention to the sequence of the attributes

2024-04-03 13:12 UTC, zsolt-wbg commented on resources/js/Pages/Auth/old/Login.vue
> +      <div class="mt-4">
You can use `gap-y-4` on the parent div instead of adding `mt-4` on every element

2024-04-03 13:17 UTC, UltraMKF12 commented on resources/js/Components/InputWithErrorAndLabel.vue
> +      <div
Can you specify the problematic part please?

2024-04-04 06:32 UTC, szabolcs3 commented on resources/js/Components/InputWithErrorAndLabel.vue
> +      <div
https://vuejs.org/guide/components/slots.html

2024-04-04 08:49 UTC, szabolcs3 approved these changes

2024-04-04 08:58 UTC, merged

2024-04-04 09:02 UTC, zsolt-wbg approved these changes