DLP-3 Medic Schedule
UltraMKF12/internship-laravel pull request #3
Opened 2024-04-23 13:37 UTC by UltraMKF12

2024-04-23 14:00 UTC, PalZsolt99-ubb requested changes

2024-04-23 14:01 UTC, szabolcs3 requested changes

2024-04-24 05:53 UTC, UltraMKF12 commented on app/Http/Controllers/RegisterScheduleController.php
> +    return inertia('RegisterSchedulePage');
But I only use inertia()? There isn't any file where I called it Inertia::render()

2024-04-24 07:20 UTC, zsolt-wbg approved these changes

2024-04-24 07:24 UTC, szabolcs3 requested changes

2024-04-24 07:24 UTC, szabolcs3 commented on app/Http/Controllers/RegisterScheduleController.php
> +    return inertia('RegisterSchedulePage');
Yeah sorry! I messed up

2024-04-24 07:40 UTC, merged